name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag srisatya123/docker-iamge-autobuild:latest
    - name: Push the docker image
      run: docker login -u srisatya123 -p ${{ secrets.DOCKER_TOKEN }} && docker push srisatya123/docker-iamge-autobuild:latest
      
